# Generated by Django 3.0.6 on 2020-05-21 19:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='My_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_post_text', models.CharField(max_length=1000)),
                ('my_post_name', models.CharField(max_length=100)),
                ('my_post_date', models.DateTimeField(default=datetime.datetime(2020, 5, 21, 22, 30, 33, 894535))),
                ('my_post_image', models.ImageField(blank=True, null=True, upload_to='posting')),
                ('my_post_tag', models.ManyToManyField(to='posting.Tag')),
            ],
        ),
    ]
