# Generated by Django 3.0.6 on 2020-05-27 17:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='my_post',
            name='my_post_rating',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='my_post',
            name='my_post_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 27, 20, 53, 42, 916388)),
        ),
    ]
