# Generated by Django 3.0.6 on 2020-05-30 12:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0003_auto_20200530_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_post',
            name='my_post_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 30, 15, 57, 7, 109421)),
        ),
    ]
